export const ShopItemsTypes = {
    FETCH_SHOP_ITEMS_START_CALL: "FETCH_SHOP_ITEMS_START_CALL",
    FETCH_SHOP_ITEMS_SUCCESS_CALL: "FETCH_SHOP_ITEMS_SUCCESS_CALL",
    FETCH_SHOP_ITEMS_FAILURE_CALL: "FETCH_SHOP_ITEMS_FAILURE_CALL",
};
